spring.application.name=EntomoEspaco

# ==============================
#           SERVER
# ==============================
server.address = ${SERVER_ADDRESS}
server.port = ${SERVER_PORT}
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force-response=true

# ==============================
#         SPRING CORE
# ==============================
# spring.profiles.active = development
spring.web.resources.add-mappings=true

# ==============================
#      DATASOURCE CONFIG
# ==============================
## Default datasource
insect.datasource.name= ${INSECT_DATASOURCE_NAME}
insect.datasource.url= ${INSECT_DATASOURCE_URL}
insect.datasource.username= ${INSECT_DATASOURCE_USERNAME}
insect.datasource.password= ${INSECT_DATASOURCE_PASSWORD}

# ==============================
#          JPA / HIBERNATE
# ==============================
spring.jpa.open-in-view = true
spring.jpa.generate-ddl=true
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.continue-on-error=true

# ==============================
#    DATE & TIME FORMATTING
# ==============================
spring.jackson.date-format = dd/MM/yyyy
spring.jackson.serialization.write_dates_as_timestamps=false
spring.gson.date-format = dd/MM/yyyy
spring.mvc.format.date = dd/MM/yyyy
spring.mvc.format.date-time = dd/MM/yyyy HH:mm:ss
spring.mvc.format.time = HH:mm:ss
spring.jackson.parser.allow-non-numeric-numbers=true

# ==============================
#        SPRING SECURITY
# ==============================
spring.security.user.name = mindsim

# ==============================
#          LOGGING (Exemplos)
# ==============================
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG
spring.mvc.log-request-details= true

# Springboot Actuator
endpoints.health.sensitive = true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
management.health.consul.enabled=false
management.health.db.enabled=true
# ==============================